//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QS2015.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QS2015.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data are compiled by the Statistical Division  from different official national and international sources..
        /// </summary>
        public static string About_Compiled_1 {
            get {
                return ResourceManager.GetString("About_Compiled_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emphasis has been placed on making the data ready for international comparison and immediate analytical use, as well as on making them easy to find..
        /// </summary>
        public static string About_Compiled_2 {
            get {
                return ResourceManager.GetString("About_Compiled_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users may be particularly interested in the statistics on CIS and central and eastern European countries, which are difficult to find elsewhere in a single integrated database..
        /// </summary>
        public static string About_Compiled_3 {
            get {
                return ResourceManager.GetString("About_Compiled_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This.
        /// </summary>
        public static string About_Glossary_1 {
            get {
                return ResourceManager.GetString("About_Glossary_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary of terms.
        /// </summary>
        public static string About_Glossary_2 {
            get {
                return ResourceManager.GetString("About_Glossary_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provides definitions for the terms used in the database..
        /// </summary>
        public static string About_Glossary_3 {
            get {
                return ResourceManager.GetString("About_Glossary_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        public static string About_Note {
            get {
                return ResourceManager.GetString("About_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some data series, e.g. data on population and employment, are available in both subject areas..
        /// </summary>
        public static string About_Note_Text_1 {
            get {
                return ResourceManager.GetString("About_Note_Text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to However these series might present slightly different values, because the different contexts may necessitate the use of different data sources and definitions..
        /// </summary>
        public static string About_Note_Text_2 {
            get {
                return ResourceManager.GetString("About_Note_Text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These sources and definitions are documented in the metadata attached to the data tables..
        /// </summary>
        public static string About_Note_Text_3 {
            get {
                return ResourceManager.GetString("About_Note_Text_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The UNECE Statistical Division uses the following major software components in the statistical software development,.
        /// </summary>
        public static string About_Software_1 {
            get {
                return ResourceManager.GetString("About_Software_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC-Axis.
        /// </summary>
        public static string About_Software_2 {
            get {
                return ResourceManager.GetString("About_Software_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string About_Software_3 {
            get {
                return ResourceManager.GetString("About_Software_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JIDE Software.
        /// </summary>
        public static string About_Software_4 {
            get {
                return ResourceManager.GetString("About_Software_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This database is maintained by the Statistical Division of the UNECE Secretariat. It provides free access to data structured to facilitate easy retrieval of statistics by users. It is organised by subject or policy areas. Multi-dimensional tables present data by country, by various socio-economic classifications related to the context, and by time period..
        /// </summary>
        public static string About_This_Database {
            get {
                return ResourceManager.GetString("About_This_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the UNECE Statistical Database.
        /// </summary>
        public static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on an indicator to view the chart.
        /// </summary>
        public static string ChartDomains_Click_Instruction {
            get {
                return ResourceManager.GetString("ChartDomains_Click_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string ChartDomains_Title {
            get {
                return ResourceManager.GetString("ChartDomains_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more countries below the chart.
        /// </summary>
        public static string Charts_Click_Instruction {
            get {
                return ResourceManager.GetString("Charts_Click_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footnote:.
        /// </summary>
        public static string Charts_Footnote {
            get {
                return ResourceManager.GetString("Charts_Footnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more data.
        /// </summary>
        public static string Charts_More_Data {
            get {
                return ResourceManager.GetString("Charts_More_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Charts_Next {
            get {
                return ResourceManager.GetString("Charts_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Charts_Previous {
            get {
                return ResourceManager.GetString("Charts_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Table.
        /// </summary>
        public static string Charts_See_Table {
            get {
                return ResourceManager.GetString("Charts_See_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Charts_Year {
            get {
                return ResourceManager.GetString("Charts_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a country to view the country profile.
        /// </summary>
        public static string Countries_Click_Instruction {
            get {
                return ResourceManager.GetString("Countries_Click_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Profiles.
        /// </summary>
        public static string Countries_Title {
            get {
                return ResourceManager.GetString("Countries_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add more countries.
        /// </summary>
        public static string CountryProfile_Add_Countries {
            get {
                return ResourceManager.GetString("CountryProfile_Add_Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string CountryProfile_Year {
            get {
                return ResourceManager.GetString("CountryProfile_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more data.
        /// </summary>
        public static string CountryRanking_More_Data {
            get {
                return ResourceManager.GetString("CountryRanking_More_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##.
        /// </summary>
        public static string CountryRanking_Numbering {
            get {
                return ResourceManager.GetString("CountryRanking_Numbering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string CountryRanking_Year {
            get {
                return ResourceManager.GetString("CountryRanking_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on an indicator to view the country ranking.
        /// </summary>
        public static string CountryRankings_Click_Instruction {
            get {
                return ResourceManager.GetString("CountryRankings_Click_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryRankings_Country {
            get {
                return ResourceManager.GetString("CountryRankings_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footnote:.
        /// </summary>
        public static string CountryRankings_Footnote {
            get {
                return ResourceManager.GetString("CountryRankings_Footnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ranking.
        /// </summary>
        public static string CountryRankings_Ranking {
            get {
                return ResourceManager.GetString("CountryRankings_Ranking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string CountryRankings_Table {
            get {
                return ResourceManager.GetString("CountryRankings_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Rankings.
        /// </summary>
        public static string CountryRankings_Title {
            get {
                return ResourceManager.GetString("CountryRankings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string CountryRankings_Value {
            get {
                return ResourceManager.GetString("CountryRankings_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footnote:.
        /// </summary>
        public static string DataMap_Footnote {
            get {
                return ResourceManager.GetString("DataMap_Footnote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover over a country.
        /// </summary>
        public static string DataMap_Hover_Country {
            get {
                return ResourceManager.GetString("DataMap_Hover_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See more data.
        /// </summary>
        public static string DataMap_More_Data {
            get {
                return ResourceManager.GetString("DataMap_More_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string DataMap_Next {
            get {
                return ResourceManager.GetString("DataMap_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data.
        /// </summary>
        public static string DataMap_No_Data {
            get {
                return ResourceManager.GetString("DataMap_No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string DataMap_Previous {
            get {
                return ResourceManager.GetString("DataMap_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string DataMap_Year {
            get {
                return ResourceManager.GetString("DataMap_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string Home_Charts {
            get {
                return ResourceManager.GetString("Home_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiles.
        /// </summary>
        public static string Home_CountryProfiles {
            get {
                return ResourceManager.GetString("Home_CountryProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rankings.
        /// </summary>
        public static string Home_CountryRanking {
            get {
                return ResourceManager.GetString("Home_CountryRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hover over a country.
        /// </summary>
        public static string Home_Hover_Country {
            get {
                return ResourceManager.GetString("Home_Hover_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string Home_Maps {
            get {
                return ResourceManager.GetString("Home_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Home_Next {
            get {
                return ResourceManager.GetString("Home_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no data.
        /// </summary>
        public static string Home_No_Data {
            get {
                return ResourceManager.GetString("Home_No_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string Home_PDF {
            get {
                return ResourceManager.GetString("Home_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Home_Previous {
            get {
                return ResourceManager.GetString("Home_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        public static string Home_Year {
            get {
                return ResourceManager.GetString("Home_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (NOTE: Log10 scale).
        /// </summary>
        public static string Logarithmic_Scale_Base_10 {
            get {
                return ResourceManager.GetString("Logarithmic_Scale_Base_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (NOTE: Log2 scale).
        /// </summary>
        public static string Logarithmic_Scale_Base_2 {
            get {
                return ResourceManager.GetString("Logarithmic_Scale_Base_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on an indicator to view the map.
        /// </summary>
        public static string MapDomains_Click_Instruction {
            get {
                return ResourceManager.GetString("MapDomains_Click_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maps.
        /// </summary>
        public static string MapDomains_Title {
            get {
                return ResourceManager.GetString("MapDomains_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a country to view the PDF country profile.
        /// </summary>
        public static string PDFProfiles_Click_Instruction {
            get {
                return ResourceManager.GetString("PDFProfiles_Click_Instruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Country Profiles.
        /// </summary>
        public static string PDFProfiles_Title {
            get {
                return ResourceManager.GetString("PDFProfiles_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shared_Banner_Home {
            get {
                return ResourceManager.GetString("Shared_Banner_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNECE.
        /// </summary>
        public static string Shared_Banner_Title {
            get {
                return ResourceManager.GetString("Shared_Banner_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © United Nations Economic Commission for Europe.
        /// </summary>
        public static string Shared_Footer_Disclaimer {
            get {
                return ResourceManager.GetString("Shared_Footer_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Shared_Icon_Home {
            get {
                return ResourceManager.GetString("Shared_Icon_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Shared_Icon_Menu {
            get {
                return ResourceManager.GetString("Shared_Icon_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABOUT DATABASE.
        /// </summary>
        public static string Shared_Menu_About {
            get {
                return ResourceManager.GetString("Shared_Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHARTS.
        /// </summary>
        public static string Shared_Menu_Charts {
            get {
                return ResourceManager.GetString("Shared_Menu_Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRY PROFILES.
        /// </summary>
        public static string Shared_Menu_Country_Profiles {
            get {
                return ResourceManager.GetString("Shared_Menu_Country_Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COUNTRY RANKINGS.
        /// </summary>
        public static string Shared_Menu_Country_Rankings {
            get {
                return ResourceManager.GetString("Shared_Menu_Country_Rankings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DATA LOCATOR.
        /// </summary>
        public static string Shared_Menu_Data_Locator {
            get {
                return ResourceManager.GetString("Shared_Menu_Data_Locator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * ENGLISH.
        /// </summary>
        public static string Shared_Menu_English {
            get {
                return ResourceManager.GetString("Shared_Menu_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GLOSSARY OF TERMS.
        /// </summary>
        public static string Shared_Menu_Glossary {
            get {
                return ResourceManager.GetString("Shared_Menu_Glossary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Shared_Menu_Home {
            get {
                return ResourceManager.GetString("Shared_Menu_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPS.
        /// </summary>
        public static string Shared_Menu_Maps {
            get {
                return ResourceManager.GetString("Shared_Menu_Maps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF PUBLICATIONS.
        /// </summary>
        public static string Shared_Menu_PDF_Publications {
            get {
                return ResourceManager.GetString("Shared_Menu_PDF_Publications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to * RUSSIAN.
        /// </summary>
        public static string Shared_Menu_Russian {
            get {
                return ResourceManager.GetString("Shared_Menu_Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STATISTICAL DIVISION.
        /// </summary>
        public static string Shared_Menu_Statistical_Division {
            get {
                return ResourceManager.GetString("Shared_Menu_Statistical_Division", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistical Database - United Nations Economic Commission for Europe.
        /// </summary>
        public static string Shared_Title {
            get {
                return ResourceManager.GetString("Shared_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string TimeSeries_Value {
            get {
                return ResourceManager.GetString("TimeSeries_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string TimeSeries_Year {
            get {
                return ResourceManager.GetString("TimeSeries_Year", resourceCulture);
            }
        }
    }
}
