var statesNames = {
    "titles": [
{ "code": "008", "name": "Albania" },
{ "code": "051", "name": "Armenia" },
{ "code": "040", "name": "Austria" },
{ "code": "031", "name": "Azerbaijan" },
{ "code": "056", "name": "Belgium" },
{ "code": "100", "name": "Bulgaria" },
{ "code": "070", "name": "Bosnia and Herzegovina" },
{ "code": "112", "name": "Belarus" },
{ "code": "124", "name": "Canada" },
{ "code": "756", "name": "Switzerland" },
{ "code": "203", "name": "Czech Republic" },
{ "code": "276", "name": "Germany" },
{ "code": "208", "name": "Denmark" },
{ "code": "724", "name": "Spain" },
{ "code": "233", "name": "Estonia" },
{ "code": "246", "name": "Finland" },
{ "code": "250", "name": "France" },
{ "code": "826", "name": "United Kingdom" },
{ "code": "268", "name": "Georgia" },
{ "code": "300", "name": "Greece" },
{ "code": "304", "name": "Greenland" },
{ "code": "191", "name": "Croatia" },
{ "code": "348", "name": "Hungary" },
{ "code": "372", "name": "Ireland" },
{ "code": "352", "name": "Iceland" },
{ "code": "376", "name": "Israel" },
{ "code": "380", "name": "Italy" },
{ "code": "398", "name": "Kazakhstan" },
{ "code": "417", "name": "Kyrgyzstan" },
{ "code": "440", "name": "Lithuania" },
{ "code": "442", "name": "Luxembourg" },
{ "code": "428", "name": "Latvia" },
{ "code": "498", "name": "Moldova" },
{ "code": "807", "name": "The former Yugoslav Republic of Macedonia" },
{ "code": "499", "name": "Montenegro" },
{ "code": "528", "name": "Netherlands" },
{ "code": "578", "name": "Norway" },
{ "code": "616", "name": "Poland" },
{ "code": "620", "name": "Portugal" },
{ "code": "642", "name": "Romania" },
{ "code": "643", "name": "Russian Federation" },
{ "code": "703", "name": "Slovakia" },
{ "code": "705", "name": "Slovenia" },
{ "code": "752", "name": "Sweden" },
{ "code": "762", "name": "Tajikistan" },
{ "code": "795", "name": "Turkmenistan" },
{ "code": "792", "name": "Turkey" },
{ "code": "804", "name": "Ukraine" },
{ "code": "840", "name": "United States" },
{ "code": "860", "name": "Uzbekistan" },
{ "code": "688", "name": "Serbia" },
{ "code": "196", "name": "Cyprus" },
{ "code": "ROW", "name": "Rest of World" },
{ "code": "438", "name": "Liechtenstein" }
    ]}
